### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JEFworks** [slowkow/picardmetrics#1]
`plot_picardmetrics.R` does not run if `picardmetrics` was run without the `-r` option so the RNAseq metrics are missing. Errors are produced since file does not exist: `Error in file(file, "rt") : cannot open the connection`

Also, it would help to have an example command for running `plot_picardmetrics.R` 
The usage in `plot_picardmetrics.R` has a typo in that it references `plot-picardmetrics.R`

**Comment by slowkow** [comment]
Thank you! Fixed in b9ada917e6b34a0fa592364f4d332d29085b22a7
