### ISSUE TITLE
Why full path?

### ISSUE THREAD

**Issue by ole-tange** [slowkow/picardmetrics#2]
"""If you have many files, or if you want to run jobs on multiple servers, it's a good idea to put the full paths in a text file."""

Why is that a good idea?

Would '--wd .' not do the right thing (if you have a shared file system)? And '--trc out' if you do not have a shared file system?

**Comment by slowkow** [comment]
Hi Ole, thanks for the tip about `--wd` and `--trc`. I was not aware of those two options when I wrote the documentation, so I thought using full paths is the way to get the correct behavior.

### Working directory

I expect that invoking GNU parallel with `--wd .` works on a shared filesystem:

```
parallel -S 1/server1,1/server2 --wd . \
  picardmetrics run -r -o out {}  ::: data/project1/sample?.bam
```

If I understand correctly, this means that `out` would be relative to the current working directory on server1 and server2. Also, the paths to input files would be relative to the current working directory on both servers.

### Transferring files

GNU parallel is able to upload a file to a remote server, run the command, and download the output files. This enables the user to use remote servers that are not connected to the current filesystem.

This might not be advisable for bioinformatics data, depending on the network connection and the size of the input files. BAM files tend to be large (hundreds of megabytes or several gigabytes).

I expect that this works when server1 and server2 do not share the current filesystem:

```
parallel -S 1/server1,1/server2 --trc out \
  picardmetrics run -r -o out {} :::: data/project1/sample?.bam
```

---

Please note I haven't executed these commands, so I might have errors. Please correct me if I do.

**Comment by ole-tange** [comment]
--wd . is a bit magical: If you are in ~/foo/bar on the local machine, then it will also use ~/foo/bar on the remote machine even if the absolute path on the local machine is /home/me/foo/bar and the absolute path on the remote is /nfs/hercules/joeuser/foo/bar.
