### ISSUE TITLE
no les

### ISSUE THREAD

**Issue by sridhar0605** [slowkow/picardmetrics#5]
Hi, 

The program 'les' is currently not installed.  To run 'les' please ask your administrator to install the package 'atm-tools'

Working on a LSF cluster, any workarounds?

**Comment by slowkow** [comment]
Sorry, `les` is not used by `picardmetrics`. I don't know what it is.

More generally, you can download and install packages as you wish (that's what I do most of the time on all of the servers that I use), or you can contact the administrator if you prefer to have them do the download and installation for you.
